# Python CircleCI 2.0 configuration file
orbs:
  heroku: circleci/heroku@1.2.2 # Invoke the Heroku orb

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Make up to start the network & the api
          command: |
            make up
# heroku cannot handle docker CI yet => circleCI could be used but requires access to docker hub and I have no time for that now. We have to deploy manually using heroku CLI container registry. cf README.md
  # deploy:
  #   docker:
  #     - image: python:3.6
  #   steps:
  #     - checkout
  #     - run:
  #         name: Deploy Master to Heroku
  #         command: |
  #           git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      # - heroku/deploy-via-git:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
